# -*- coding: utf-8 -*-
"""deepface face recognition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQx718rZra54sWvawMsFEkBPe3YQf5dk
"""

pip install deepface

from deepface import DeepFace
import matplotlib.pyplot as plt 
import pandas as pd

img1_path =  "/content/drive/MyDrive/face dataset/img1.jpg"
img2_path =  "/content/drive/MyDrive/face dataset/img2.jpg"

img1 = DeepFace.detectFace(img1_path)
img2 = DeepFace.detectFace(img2_path)

plt.imshow(img1)

plt.imshow(img2)

model_name = "Facenet"

resp = DeepFace.verify(img1_path=img1_path , img2_path=img2_path, model_name= model_name)

resp

df =  DeepFace.find(img_path = "/content/drive/MyDrive/face dataset/source.jfif" , db_path = "/content/drive/MyDrive/face dataset")

df.head()

obj = DeepFace.analyze(img1_path)

plt.imshow(img1)

obj

